### ISSUE TITLE
请问const configuration = {iceServers: [{url: 'stun:stun.l.google.com:19302'}]};有没有都可以是为什么

### ISSUE THREAD

**Issue by lw1997liuwei** [baconcheese113/react-native-webrtc-minimal#1]
const configuration = {iceServers: [{url: 'stun:stun.l.google.com:19302'}]}; 这个代码不是我们链接的服务器的地址吗?
我把这个地址随便输入，也可以，删除这行代码，也可以，这是为什么，是您源码给重定向了吗

**Comment by baconcheese113** [comment]
Hey LW, 

That is the address of a STUN server provided for free by google. [It allows NAT clients to connect to each other.](https://www.3cx.com/pbx/what-is-a-stun-server/) Though you probably can remove it for the example I provided....for almost every implementation beyond this simple example you'll need to use a STUN server. 

I found the ICE configuration to be confusing when I started with webRTC, so I've included the typical ICE config as a starting point.
