### ISSUE TITLE
How to use it with live server.

### ISSUE THREAD

**Issue by soban1234** [baconcheese113/react-native-webrtc-minimal#10]
Hi, i'm new to react native, can someone please guide me how to use this with live server and just like phone calls, right now at what i am speaking in mic is being listen in speaker. it should work like real calls, how to achieve that?

**Comment by baconcheese113** [comment]
Added a new section to the readme https://github.com/baconcheese113/react-native-webrtc-minimal#next-steps

You can check my post here https://react-native-webrtc.discourse.group/t/testing-react-native-webrtc/436 and search the forum for other more relevant posts to your question
