### ISSUE TITLE
any minimal example with signaling server ?

### ISSUE THREAD

**Issue by AmirDoreh** [baconcheese113/react-native-webrtc-minimal#15]
firstly thanks for you minimal example .
do you have any other minimal example with signaling server ?

**Comment by baconcheese113** [comment]
Nah, there's a ton of variables around what signaling server to use and how to implement it. You can look at some example code from my main webrtc project here:

https://github.com/baconcheese113/chat2gether/blob/master/server/src/socket.js
https://github.com/baconcheese113/chat2gether/blob/master/client/src/helpers/socketHelper.js

I'd appreciate stars on any of my repos that help you!
