### ISSUE TITLE
How can we do one-to-one video call using this?

### ISSUE THREAD

**Issue by sainath-everest** [baconcheese113/react-native-webrtc-minimal#2]
I tried this code and it opens video in my end. I have back end go server, which we can connect to using web sockets. How can i use that server as central for this video streaming?

**Comment by baconcheese113** [comment]
https://react-native-webrtc.discourse.group/t/simplest-example-possible/302/15

**Comment by sainath-everest** [comment]
I got this example from this link itself https://react-native-webrtc.discourse.group/t/simplest-example-possible/302/15 ?

**Comment by baconcheese113** [comment]
That should cover the majority of it. The issues section isn't really the place to ask for a full tutorial outside the scope of the repo, but do you have any specific questions?

**Comment by sainath-everest** [comment]
I have tried your webrtc sample example.Can you give some inputs on how to integrate with this my back end server .Like how to stream to specific client.You mentioned signalling server what's that mean?If you have problem with asking questions here in issues section then can I post this in link that you shared.Is that your blog ?
