### ISSUE TITLE
TypeError: null is not an object

### ISSUE THREAD

**Issue by KaushikSathvara** [baconcheese113/react-native-webrtc-minimal#5]
When I press the click to start stream it is saying type error null is not an object. I think the app might not get the camera permission.
here is an error log.
```
[Mon Apr 06 2020 12:04:41.462]  WARN     Possible Unhandled Promise Rejection (id: 12):
TypeError: null is not an object (evaluating 'WebRTCModule.enumerateDevices')

```

**Comment by baconcheese113** [comment]
What are you testing with?

**Comment by KaushikSathvara** [comment]
>What are you testing with?

With my Android device.

Solved when I reinitialize repo and then npm install and then run, it worked. But still got error of null object in another project if I use code from App.js file. 

Is there any specific permission I have to give if I want to take the script from the App.js file?

**Comment by baconcheese113** [comment]
Your permissions are here in android https://github.com/baconcheese113/react-native-webrtc-minimal/blob/master/android/app/src/main/AndroidManifest.xml

iOS setup is here https://github.com/baconcheese113/react-native-webrtc-minimal/commit/b7785e5e2abea2b780e68a640645415b3479b1c7

**Comment by KaushikSathvara** [comment]
After installing react-native-webrtc my application is not starting and crashing, when I uninstall react-native-webrtc it did not crash.

**Comment by baconcheese113** [comment]
There could be many reasons for that in a different project, are you saying this project doesn't work when you `npm i` or `yarn`?

**Comment by KaushikSathvara** [comment]
**Your project is completely working** but When I setup new project and install react-native-webrtc as a dependency and when I use it's webrtc.enumaratedevices function, it returns me null value.

**Comment by KaushikSathvara** [comment]
May be that was react-native linking issue after linking react-native-webrtc package to project, script is successfully access camera.

Thank you @baconcheese113
