### ISSUE TITLE
你好，我下载并成功运行了 只能看到本地的视频，远端视频流如何配置 如何实现两个手机互相聊天呢？谢谢

### ISSUE THREAD

**Issue by TheOneT1** [baconcheese113/react-native-webrtc-minimal#7]

**Comment by baconcheese113** [comment]
> Hello, I downloaded and ran it successfully. I can only see the local video. How to configure the remote video stream? Thank you

The remote video is the bottom video window. You start the call with the button at the top.

If your question is about implementing a signalling server, that's out of the scope of this example.
